import { PropsWithChildren } from "react";
import Header from "./Header";
import Head from "next/head";

const Layout = ({ children }: PropsWithChildren) => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="pb-20 pt-28">{children}</div>
    </>
  );
};

export default Layout;
